Repository DMSport/DMSport-Frontend, pull requests merged in 2022-11, with the labels that each got.

#29 Feat :: 헤더, 로그인 회원가입 기능구현
  package-lock.json
  package.json
  src/App.tsx
  src/Components/Header/Header.style.ts
  src/Components/Header/Header.tsx
  src/Components/Notice/Button.tsx
  src/Components/Notice/NoticeModal.tsx
  src/Components/Notice/Post.tsx
  src/Components/Sign/Certification.tsx
  src/Components/Sign/SignIn/SignIn.tsx
  src/Components/Sign/SignUp/Certification.tsx
  src/Components/Sign/SignUp/SignUp.tsx
  src/Pages/NoticePage.tsx
  src/Router.tsx
  src/Store/atoms.ts
Labels: Feat

#34 Feat :: 비밀번호 번경 페이지 기능구현
  src/Components/Sign/ChangePw/ChangePw.tsx
  src/Components/Sign/ChangePw/FYPCerti.tsx
Labels: Feat

#37 Docs :: CleanCode 및 로그아웃 버그 수정
  src/Components/Footer/Footer.tsx
  src/Components/Header/Header.tsx
  src/Components/My/Button/MyButton.tsx
  src/Components/Privacy/Privacy.tsx
  src/Components/Privacy/PrivacyPolicy.tsx
  src/Components/Sign/ChangePw/ChangePw.tsx
  src/Components/Sign/ChangePw/FYPCerti.tsx
  src/Components/Sign/SignIn/SignIn.tsx
  src/Components/Sign/SignUp/Certification.tsx
  src/Components/Sign/SignUp/SignUp.tsx
  src/Store/atoms.ts
Labels: CleanUp

#39 Fix :: SignUp 버그 수정
  src/Components/Sign/SignUp/SignUp.tsx
Labels: Fix

#38 feat :: 공지페이지 기능 구현
  package-lock.json
  package.json
  src/Components/Header/Header.tsx
  src/Components/Notice/Button.tsx
  src/Components/Notice/ModalContent.tsx
  src/Components/Notice/NoticeModal.style.ts
  src/Components/Notice/NoticeModal.tsx
  src/Components/Notice/Post.tsx
  src/Components/Sign/SignUp/Certification.tsx
  src/Components/Sign/SignUp/SignUp.tsx
  src/Hooks/useInput.tsx
  src/Pages/MyPage.tsx
  src/Pages/NoticePage.tsx
  src/Pages/NoticePage/NoticePage.style.ts
  src/Pages/NoticePage/NoticePage.tsx
  src/Router.tsx
  src/Store/atoms.ts
  src/Utils/ClubType.ts
  src/Utils/Function/Timer.ts
  src/Utils/api/my.ts
  src/Utils/api/notice.ts
  src/Utils/axios/axios.ts
  src/index.tsx
Labels: Feat

#41 Fix :: 헤더 버그 고침
  src/Components/Header/Header.tsx
Labels: Fix

#50 Fix :: 헤더 Fix
  src/Components/Header/Header.tsx
Labels: Fix

#54 Feat :: 클럽 정지 페이지 퍼블리싱 및 기능구현
  src/Assets/SVG/Badminton.svg
  src/Assets/SVG/Basketball.svg
  src/Assets/SVG/Soccer.svg
  src/Assets/SVG/Volleyball.svg
  src/Components/ManageSportsClub/ClubBan/BanPage.style.ts
  src/Components/ManageSportsClub/ClubBan/BanPage.tsx
  src/Components/ManageSportsClub/studentsearch/StudentSearch.style.ts
  src/Components/Sign/SignIn/SignIn.tsx
  src/Pages/adminpage/adminPage.tsx
  src/Router.tsx
Labels: Feat

#65 Feat :: Title 및 대표 사진 변경
  public/index.html
Labels: Feat
